 <div class="page-title">
    <h1>Something went wrong. Please try again</h1>
</div>


<div class="buttons-set">
    <button type="button" class="button" title="Continue Shopping" onclick="window.location='<?php echo Mage::getBaseUrl(); ?>'"><span><span>Continue Shopping</span></span></button>
</div>
                </div>

<?php Mage::getSingleton('core/session')->setOrderIncrementId(""); ?>
<?php Mage::getSingleton('core/session')->setOrderId(""); ?>                