<style type="text/css">
	.cart-collaterals .cart-installment{text-align: right!important;display: block;margin-right: 15px;}
</style>
<div class="sip_splitprice">
<?php  

	$current_url = $this->helper('core/url')->getCurrentUrl();
	if(stripos($current_url, 'checkout')){
		$current_page = 'checkout';
	}
	if (Mage::registry('current_category')){
	  // category page
		$current_page = 'category';
	}
	if(Mage::registry('current_product')) {
	  // Product detail page
		$current_page = 'product';
	}
	$extensionEnabled = Mage::getStoreConfig('payment/pis_cc/active');
	$enableInstallmentPrice = Mage::getStoreConfig('payment/pis_cc/enable_installment_price');
	if($extensionEnabled == 1 && $enableInstallmentPrice == 1){
		$allowed_page = explode(",",Mage::getStoreConfig('payment/pis_cc/installment_price_on_pages'));
		$divider = Mage::getStoreConfig('payment/pis_cc/installments_count');	
		// installment price text from Translation
		$text = Mage::helper('pis_payment')->getInstallmentPriceText("pis_cc");
	}else{
		$extensionEnabled = Mage::getStoreConfig('payment/pis_paymentform/active');
		$enableInstallmentPrice = Mage::getStoreConfig('payment/pis_paymentform/enable_installment_price');
		$allowed_page = explode(",",Mage::getStoreConfig('payment/pis_paymentform/installment_price_on_pages'));
		$divider = Mage::getStoreConfig('payment/pis_paymentform/installments_count');
		// installment price text from Translation
		$text = Mage::helper('pis_payment')->getInstallmentPriceText("pis_paymentform");	
	}

	

	
	

	//$text = Mage::getStoreConfig('payment/pis_cc/installment_price_text');

	$currentCurrencyCode = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();

	if($extensionEnabled == 1 && $enableInstallmentPrice == 1 && in_array($current_page, $allowed_page)){
		if($current_page == "cart" || $current_page=="checkout"){
			$segment = ROUND((float)Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal() / $divider,2);
			echo $this->getChildHtml('child');
		}else{
			if($current_page == 'category'){
				$_product = $this->getProduct();
				$formattedPrice = Mage::helper('core')->currency($_product->getFinalPrice(), false, false);

				$segment = ROUND((float)$formattedPrice / $divider,2);
				//$segment = ROUND((float)$_product->getFinalPrice() / $divider,2);
				echo $this->getChildHtml('child'.$this->getProduct()->getId());
			}
			if($current_page == 'product'){
				$_product = $this->getProduct();
				$formattedPrice = Mage::helper('core')->currency($_product->getFinalPrice(), false, false);
				
				$segment = ROUND((float)$formattedPrice / $divider,2);
				//$segment = ROUND((float)$_product->getFinalPrice() / $divider,2);
				echo $this->getChildHtml('child'.$this->getProduct()->getId());	
			}
			
		}
		echo "<span class='cart-installmentss' >".$currentCurrencyCode.$segment." x ".$divider." ".$text."</span>"; 	
	} else {
		if($current_page == "cart" || $current_page=="checkout"){
			echo $this->getChildHtml('child');
		}else{
			echo $this->getChildHtml('child'.$this->getProduct()->getId());
		}
	}
?>
</div>
