<div class="post-content">
    <div class="fusion-title title" style="padding-left: 20px;"><h1 class="title-heading-left">Customer’s Terms and Conditions</h1>

        <div class="title-sep-container">
            <div class="title-sep sep-double sep-solid"></div>
        </div>
    </div>
    <ol style="list-style: outside inside; padding-left: 40px;">
        <li>Buyer who’s name appears below (“Buyer”, “You”, or “Your) promises to pay the full amount of the Total
            Authorized Purchase Price in the number of installment payments set forth in the Recurring Installment
            Payment Authorization (“Authorization”) to Seller (“Seller”, “We” or “Us”) by authorizing Seller to charge
            Buyer’s credit card in equal monthly installments as set forth in the Authorization (each an “Installment”)
            each month until paid in full.&nbsp; Buyer further agrees that Seller will receive authorization for the
            full amount of the purchase on Buyer’s credit card at the time of sale, and will authorize the remaining
            balance each month thereafter until paid in full.&nbsp; Buyer understands that this authorization will
            remain in effect until Buyer cancels it in writing.
        </li>
        <li>&nbsp;Buyer agrees to notify Seller in writing via Buyer’s user account at&nbsp;<a
                href="https://consumer.splitit.com/">consumer.splitit.com</a>&nbsp;of any changes to Buyer’s
            credit card account information or termination of this authorization. We will update such information and
            process such requests within 30 days after our receipt of such request.&nbsp; Buyer understands that the
            Installment payments may be authorized and charged on the next business day.&nbsp; Buyer further understands
            that because these are electronic transactions, any authorizations and charges may be posted to Your account
            as soon as the Installment payment dates.
        </li>
        <li>Any Installment amounts due under this contract that have been charged to Buyer’s credit card and not paid
            when due, pursuant to Your agreement with Your credit card issuer (“Issuer”), will be charged interest at
            the Annual Percentage Rate stated in Your Issuer’s Federal Truth-in-Lending Disclosure statement until the
            Installments are fully paid.&nbsp; So long as You timely pay each Installment to Your Issuer when due,
            Issuer will not charge Buyer interest on such Installment.&nbsp; Issuer may charge Buyer interest on any
            other balance You may have on Your credit card in excess of the Installment amount.
        </li>
        <li>In the case of an authorization being rejected for any reason, Buyer understands that Seller may, in its
            discretion, attempt to process the charge again within five (5) days.
        </li>
        <li>In the event that Buyer’s Issuer fails to pay an Installment for any reason, Seller, at its discretion, may
            charge Buyer’s credit card at any time for the full outstanding amount due.
        </li>
        <li>In consideration for services provided by Pay It Simple USA, Inc. (“Splitit”) to Seller, Buyer agrees
            that Splitit will have the right to communicate with and solicit Buyer via e-mail (or other means).&nbsp;
            This provision is operational for not less than five (5) years from the date of the initial authorization.
        </li>
        <li>Buyer understands that Splitit is not a party to this Agreement, which is solely between Buyer and
            Seller.
        </li>
        <li>Buyer understands and agrees that Splitit is not responsible for the delivery and quality of goods
            purchased in this transaction.
        </li>
        <li>Buyer acknowledges that the origination of any authorized transactions to the Buyer’s account must comply
            with the provisions of U.S. law.&nbsp;&nbsp;Buyer certifies that Buyer is an authorized user of the credit
            card utilized for this transaction and the Installments and will not dispute these transactions with Buyer’s
            credit card company, so long as the authorizations correspond to the terms indicated in the authorization
            form.
        </li>
        <li>Buyer agrees that if delivery of the goods or services are not made at the time of execution of this
            contract, the description of the goods or services and the due date of the first Installment may be inserted
            by Seller in Seller’s counterpart of the contract after it has been signed by Buyer.
        </li>
        <li>If any provision of this contract is determined to be invalid, it shall not affect the remaining provisions
            hereof.
        </li>
        <li>PRIVACY POLICY.&nbsp; Buyer’s privacy is important to us.&nbsp; You may obtain a copy of Splitit’s
            Privacy Policy by visiting their website at consumer.splitit.com.&nbsp; As permitted by law, We and
            Splitit may share information about our transactions and experiences with Buyer with other affiliated
            companies and unaffiliated third parties, including consumer reporting agencies and other creditors.
            However, except as permitted by law, neither We nor Splitit may share information which was obtained
            from credit applications, consumer reports, and any third parties with companies affiliated with us if Buyer
            instructs us not to share this information.&nbsp; If Buyer does not want us to share this information, Buyer
            shall notify us in writing via Buyer’s user account at&nbsp;<a href="https://consumer.splitit.com/">consumer.splitit.com</a>&nbsp;using
            the password Buyer was provided with for such notification and for accessing information on Splitit’s
            website.&nbsp; Buyer shall include Buyer’s name, address, account number and the last four digits of Buyer’s
            credit card number used in this transaction so such request can be honored. We may report about Your account
            to consumer reporting agencies.&nbsp; Late payments, missed payments, or other defaults on Your credit card
            account may be reflected by Your Issuer in Your credit report.
        </li>
        <li>ARBITRATION. Any claim, dispute or controversy (“Claim”) arising from or connected with this Agreement,
            including the enforceability, validity or scope of this arbitration clause or this Agreement, shall be
            governed by this provision. Upon the election of Buyer or Seller by written notice to the other party, any
            Claim shall be resolved by arbitration before a single arbitrator, on an individual basis, without resort to
            any form of class action (“Class Action Waiver”), pursuant to this arbitration provision and the applicable
            rules of the American Arbitration Association (“AAA”) in effect at the time the Claim is filed.&nbsp; Any
            arbitration hearing shall take place within the State of New York, County of New York. At the written
            request of Buyer, any filing and administrative fees charged or assessed by the AAA which are required to be
            paid by Buyer and that are in excess of any filing fee Buyer would have been required to pay to file a Claim
            in state court in New York shall be advanced and paid for by Seller.&nbsp; The arbitrator may not award
            punitive or exemplary damages against any party.&nbsp; IF ANY PARTY COMMENCES ARBITRATION WITH RESPECT TO A
            CLAIM, NEITHER BUYER OR SELLER WILL HAVE THE RIGHT TO LITIGATE THAT CLAIM IN COURT OR HAVE A JURY TRIAL ON
            THAT CLAIM, OR TO ENGAGE IN PRE-ARBITRATION DISCOVERY, EXCEPT AS PROVIDED FOR IN THE APPLICABLE ARBITRATION
            RULES.&nbsp; FURTHER, BUYER WILL NOT HAVE THE RIGHT TO PARTICIPATE AS A REPRESENTATIVE OR MEMBER OF ANY
            CLASS OF CLAIMANTS PERTAINING TO THAT CLAIM, AND BUYER WILL HAVE ONLY THOSE RIGHTS THAT ARE AVAILABLE IN AN
            INDIVIDUAL ARBITRATION.&nbsp; THE ARBITRATOR’S DECISION WILL BE FINAL AND BINDING ON ALL PARTIES, EXCEPT AS
            PROVIDED IN THE FEDERAL ARBITRATION ACT (“the FAA”).&nbsp; This Arbitration Provision shall be governed by
            the FAA, and, if and where applicable, the internal laws of the State of New York. If any portion of this
            Arbitration provision is deemed invalid or unenforceable, it shall not invalidate the remaining portions of
            this Arbitration provision or the Agreement, provided however, if the Class Action Waiver is deemed invalid
            or unenforceable, then this entire Arbitration provision shall be null and void and of no force or effect,
            but the remaining terms of this Agreement shall remain in full force and effect.&nbsp; Any appropriate court
            having jurisdiction may enter judgment on any award.
        </li>
    </ol>

</div>