<script type="text/javascript">

    //<![CDATA[
    function checkForUpdates() {
        /*new Ajax.Request('<?php //echo $this->checkforupdates() ?>', {
            method:     'get',
            onSuccess: function(transport){
                alert(transport.responseText)
            }
        });*/
        
        var siteLanguageArr = [];
        jQuery("#payment_pis_cc_select_language > option").each(function() {
            siteLanguageArr.push(this.value);
        });
        var splititFallbackLanguageArr = [];
        var splititLang = "";
        jQuery("#payment_pis_cc_splitit_fallback_language > option").each(function() {
            splititLang = this.value;
            splititFallbackLanguageArr.push(splititLang.split('-').join('_'));
        });
        
        var languageId = "";
        jQuery.each( siteLanguageArr, function( index, value ){
            languageId = String(value);
            if(jQuery.inArray(languageId, splititFallbackLanguageArr) !== -1){
                jQuery("#loading-mask").show();
                new Ajax.Request('<?php echo $this->checkforupdates() ?>', {
                    method: 'get',
                    dataType: 'json',
                    asynchronous: false,
                    parameters:{"language":languageId.split('_').join('-')},
                    onSuccess: function(transport){
                        //console.log(transport.responseText);
                        var result = JSON.parse(transport.responseText);

                        var i = 0;
                        console.log(result);
                        jQuery("table#languages_table_"+languageId+" > tbody > tr").each(function(){

                          var edited = jQuery(this).find("td:eq(2) input[type='hidden']").val();
                          
                          if(edited != "1"){
                            var keyData = jQuery(this).find("td:eq(0) input[type='text']").val();
                            jQuery(this).find("td:eq(2) input[type='text']").val(result[keyData]);
                          }
                          i++;
                        });
                    }
                });
            }
        });
    }
    //]]>
</script>


<?php echo $this->getButtonHtml() ?>